services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      # 볼륨 추가하기 모노 레포 빌드 파일 나중에 여기 추가해야함 -김민규-
    networks:
      - nginx-net
    restart: unless-stopped
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
    networks:
      - nginx-net

volumes:
  jenkins_home:

networks:
  nginx-net:
    external: true