services:
  pang-server-blue:
    container_name: pang-server-blue
    image: pangstream/pang-api-server:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://pang-server-blue/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - nginx-net

  pang-server-green:
    container_name: pang-server-green
    image: pangstream/pang-api-server:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://pang-server-green/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - nginx-net

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-net
    restart: unless-stopped

networks:
  nginx-net:
    driver: bridge