name: deploy-folder

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
      remote_path:
        required: true
        type: string
    secrets:
      HOST:
        required: true
      USERNAME:
        required: true
      KEY:
        required: true
      PORT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: ${{ inputs.folder }}
          remote_path: ${{ inputs.remote_path }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
          remote_port: ${{ secrets.PORT }}