name: deploy docker compose on server

on:
  push:
    branches:
      - main
    paths:
      - 'jenkins/**'
      - 'main/**'

jobs:
  deploy-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if file
        id: check_files
        uses: tj-actions/verify-changed-files@v20
        with:
          files: /jenkins/**

      - name: Deploy to Jenkins Server
        if: steps.check_files.outputs.files_changed == 'true'
        uses: ./.github/workflows/deploy-folder.yml
        with:
          folder: /jenkins
          remote_path: ${{ secrets.FOLDER_DIRECTORY }}
          HOST: ${{ secrets.JENKINS_HOST }}
          USERNAME: ${{ secrets.JENKINS_USERNAME }}
          KEY: ${{ secrets.JENKINS_KEY }}
          PORT: ${{ secrets.JENKINS_PORT }}